#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

TAG=${TAG:-test} buildxCmd bake $setFlags --load mainline

set -o pipefail -x
docker run --rm --privileged tonistiigi/binfmt:${TAG:-test} --uninstall qemu-*
status=$(docker run --rm --privileged tonistiigi/binfmt:${TAG:-test} --install all)

echo $status | jq .supported | grep linux/arm64
echo $status | jq .supported | grep linux/amd64
echo $status | jq .supported | grep linux/arm/v7
echo $status | jq .supported | grep linux/arm/v6
echo $status | jq .supported | grep linux/riscv64
echo $status | jq .supported | grep linux/ppc64le
echo $status | jq .supported | grep linux/386

echo $status | jq .emulators | grep qemu-riscv64
echo $status | jq .emulators | grep qemu-arm

docker run --rm arm32v7/alpine uname -a

if [ "$(uname -m)" != "x86_64" ]; then exit 0; fi

status=$(docker run --rm --privileged tonistiigi/binfmt:${TAG:-test})

echo $status | jq .supported | grep linux/arm/v7
echo $status | jq .emulators | grep qemu-arm
