name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 8 */6 * *' # every 6 days
  workflow_dispatch:
  push:

env:
  REPO_SLUG: HalleyAssist/binfmt
  CACHE_GHA_SCOPE: binfmt
  CACHE_GHA_SCOPE_CROSS: binfmt-cross

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - mainline
          - buildkit
          - desktop
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Expose GitHub Runtime
        uses: HalleyAssist/ghaction-github-runtime@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Warm cache
        run: |
          ./hack/warm-cache ${{ matrix.target }}
        env:
          CACHE_FROM: type=gha,scope=${{ env.CACHE_GHA_SCOPE }}-${{ matrix.target }}
          CACHE_TO: type=gha,scope=${{ env.CACHE_GHA_SCOPE }}-${{ matrix.target }}

  validate:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        script:
          - ./hack/lint
          - ./hack/validate-vendor
          - ./hack/install-and-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Expose GitHub Runtime
        uses: HalleyAssist/ghaction-github-runtime@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Run
        run: |
          ${{ matrix.script }}
        env:
          CACHE_FROM: type=gha,scope=${{ env.CACHE_GHA_SCOPE }}-mainline

  build:
    runs-on: ubuntu-latest
    #needs:
    #  - validate
    strategy:
      fail-fast: false
      matrix:
        target:
          - mainline
          - buildkit
          - desktop
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REPO_SLUG }}
          tags: |
            type=ref,event=branch,enable=${{ matrix.target == 'mainline' }}
            type=ref,event=branch,prefix=${{ matrix.target }}-,enable=${{ matrix.target != 'mainline' }}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.title=Binfmt
            org.opencontainers.image.description=Cross-platform emulator collection distributed with Docker images
          bake-target: meta-helper
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config: .github/buildkit.toml
          buildkitd-flags: --allow-insecure-entitlement=security.insecure

      - name: Log into registry
        run: echo "${{ secrets.dockerhub_token }}" | docker login -u splitice --password-stdin
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Build ${{ matrix.target }}
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: ${{ matrix.target }}-all
          push: ${{ startsWith(github.ref, 'refs/heads/') }}
          set: |
            *.cache-from=type=gha,scope=${{ env.CACHE_GHA_SCOPE_CROSS }}-${{ matrix.target }}
            *.cache-from=type=gha,scope=${{ env.CACHE_GHA_SCOPE }}-${{ matrix.target }}
            *.cache-to=type=gha,scope=${{ env.CACHE_GHA_SCOPE_CROSS }}-${{ matrix.target }}
